version: '3.7'

services:
  app:
    build: .
    container_name: notelink-app
    restart: always
    command: sh -c "alembic upgrade head &&
                    uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/notelink
    ports:
      - "8005:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: notelink-db
    restart: on-failure
    env_file:
      - ./envs/db.env
    ports:
      - "5435:5432"
